title: Jamie Houston
description: A blog about development tools, tips, and tech adventures
author: Jamie Houston
email: jamie.houston@gmail.com
baseurl: ""
url: "https://houstonthings.com"

# Build settings
markdown: kramdown
highlighter: rouge
remote_theme: startbootstrap/startbootstrap-clean-blog-jekyll

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# Posts settings
permalink: /:categories/:year/:month/:day/:title:output_ext

# Pagination
paginate: 5
paginate_path: "/page/:num/"

# Social links
github_username: jamie-houston

# Clean Blog theme settings
clean_blog:
  # Site description for meta tags
  description: "A blog about development tools, tips, and tech adventures"
  
  # Navigation
  navigation:
    - title: "Home"
      url: "/"
    - title: "Resume"
      url: "/resume"
    - title: "About"
      url: "/about"

# Header pages
header_pages:
  - index.md
  - resume.md

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache