title: Jamie Houston
description: A blog about development tools, tips, and tech adventures
author: Jamie Houston
email: jamie.houston@gmail.com
baseurl: ""
url: "https://houstonthings.com"

# Build settings
markdown: kramdown
highlighter: rouge
remote_theme: "StartBootstrap/startbootstrap-clean-blog-jekyll@v5.0.11"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme

# Posts settings
permalink: /:categories/:year/:month/:day/:title:output_ext

# Pagination
paginate: 5
paginate_path: "/page/:num/"

# Social links
github_username: jamie-houston

# Google Analytics
google_analytics: G-L2NJ2WBR4S

# Clean Blog theme doesn't use header_pagesL2NJ2WBR4
# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache